exhibition/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='index')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

main/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.ExhibitionsView.as_view(), name='home'),
    path('category/<int:category_id>/', views.ExhibitionsView.as_view(), name='category'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.exhibition_detail, name='exhibition_detail'),
    path('<int:id>/edit/', views.exhibition_edit, name='exhibition_edit'),
    path('<int:id>/delete/', views.exhibition_delete, name='exhibition_delete'),

]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('delete_acc/', views.delete_account, name='delete_acc'),
    path('edit_acc/', views.edit_acc, name='edit_acc'),
    path('verify/<str:token>/', views.EmailVerificationView, name='verify'),
]

main/models.py
from django.db import models
from users.models import User

class ArticleCategory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категория'

class Articles(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    image = models.FileField()
    name = models.CharField(max_length=125)
    description = models.TextField()
    category = models.ForeignKey(to=ArticleCategory, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/exhibition/{self.id}'

    class Meta:
        verbose_name = 'Выставка'
        verbose_name_plural = 'Выставки'

class Comment(models.Model):
    article = models.ForeignKey(to=Articles, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms
from .models import Articles, Comment

class ArticlesForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Название'
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Описание'
    }))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'form-control', 'placeholder': 'Вставьте изображение для выставки'
    }))
    category = forms.Select(attrs={
        'class': 'form-select bg-light', 'placeholder': 'Категория'
    })
    class Meta:
        model = Articles
        fields = ['name', 'image', 'category', 'description']

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Leave a comment...'
    }))
    class Meta:
        model = Comment
        fields = ['text']

main/mixin/views.py
class TitleMixin:
    title = 'exhibition'
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = self.title
        return context

main/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import Articles, ArticleCategory, Comment
from .forms import ArticlesForm, CommentForm
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from .mixin.views import TitleMixin


class ExhibitionsView(TitleMixin, ListView):
    model = Articles
    template_name = 'main/index.html'
    paginate_by = 15
    title = 'Exhibitions list'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['categories'] = ArticleCategory.objects.all()
        return context


# class ExbCreateView(TitleMixin, CreateView):
#     model = Articles
#     template_name = 'main/create.html'
#     title = 'Exb Create Page'
#     form_class = ArticlesForm
#

def create(request):
    if request.method == 'POST':
        form = ArticlesForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            exb = form.save(commit=False)
            exb.user = request.user
            exb.save()
            return redirect('articles:home')
        else:
            print(form.errors)
    else:
        form = ArticlesForm()
    return render(request, 'main/create.html', {'form': form})

def exhibition_detail(request, id):
    article = get_object_or_404(Articles, id=id)
    comment = Comment.objects.filter(article=article)
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            com = form.save(commit=False)
            com.article = article
            com.user = request.user
            com.save()
        else:
            print(form.errors)
    else:
        form = CommentForm()
    return render(request, 'main/exhibition_detail.html', {'article': article, 'comment': comment, 'form': form})


def exhibition_edit(request, id):
    article = get_object_or_404(Articles, id=id)
    if request.method == 'POST':
        form = ArticlesForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:exhibition_detail', id=article.id)
    else:
        form = ArticlesForm(instance=article)
    return render(request, 'main/exhibition_edit.html', {'form': form, 'article': article})

def exhibition_delete(request, id):
    article = get_object_or_404(Articles, id=id)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:exhibitions')
    return render(request, 'main/exhibition_delete.html', {'article': article})

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-secondary-subtle">
    <nav class="navbar navbar-expand-lg navbar bg-dark">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand text-light" href="{%url 'articles:home'%}">SmartArchieve</a>
            <!-- Toggler for mobile view -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navigation Links -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-light" aria-current="page" href="{% url 'articles:home' %}"><i class="fas fa-home"></i> Главная</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item text-dark" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item text-ligh" href="orders/orders.html">Мои выставки</a></li>
                        {% if user.is_superuser or user.is_staff %}
                            <li><a class="dropdown-item text-ligh" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item text-ligh" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'articles:create' %}">
                            <i class="fa-regular fa-square-plus"></i> Добавить выставку
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h1 class="mt-5 text-center">Создайте выставки</h1>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                                <div class="mb-3">
                                  <label for="{{form.image.id_for_label}}" class="form-label">Изображение</label>
                                    {{form.image}}
                                </div>
                                <div class="mb-3">
                                  <label for="{{form.name.id_for_label}}" class="form-label">Название</label>
                                  {{form.name}}
                                </div>
                                <div class="mb-3">
                                  <label for="{{form.description.id_for_label}}" class="form-label">Описание</label>
                                  {{form.description}}
                                </div>
                                <label class="form-label" for="{{form.category.id_for_label}}">Категория:</label>
                                {{form.category}}
                                <button type="submit" class="btn btn-success w-100 mt-3">Создать</button>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/exhibition.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <div class="sidebar">
        <div class="sidebar-header">Категории</div>
        {% for category in categories %}
            <a href="{% url  'articles:category' category.id %}">{{ category.name }}</a>
        {% endfor %}
    </div>

    <!-- Контент -->
    <div class="container py-5" style="margin-left: 240px;"> <!-- Отступ для бокового меню -->
        <h1 class="text-center mb-5">Выставки</h1>
        <div class="row gy-4">
            {% if object_list %}
                {% for el in object_list %}
                <!-- Карточка 1 -->
                <div class="col-md-4 col-sm-6">
                    <div class="card">
                        <img src="{{ el.image.url }}" alt="Выставка" class="card-img-top">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ el.name }}</h5>
                            <a class="btn btn-light" href="{% url 'articles:exhibition_detail' id=el.id %}">Посмотреть выставку</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p>На этой странице пока нету выставок</p>
            {% endif %}
        </div>
    </div>


    <nav aria-label="...">
  <ul class="pagination">
      {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
    </li>
      {%endif%}
      {%for page in paginator.page_range%}
    <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
      {%endfor%}
      {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
    </li>
      {%endif%}
  </ul>
</nav>
{% endblock %}

main/templates/main/exhibition_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Удалить выставку</h1>
    <p>Вы уверены, что хотите удалить "{{ article.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Удалить</button>
    </form>
    <a href="{% url 'exhibition_detail' article.id %}" class="btn btn-secondary">Отмена</a>
{% endblock %}

main/templates/main/exhibition_detail.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Main Image -->
                <img src="{{article.image.url}}" class="img-fluid rounded shadow-sm mb-4" alt="Exhibition Image">

                <!-- Exhibition Details -->
                <div class="mb-4">
                    <div class="d-flex justify-content-between align-items-center">
                        <h1 class="mb-3">{{article.name}}</h1>
                    </div>
                    <p class="text-muted">Created on {{article.created}} by <a href="#" class="text-decoration-none">{{article.user.username}}</a></p>
                    <p class="lead">{{article.description}}</p>
                </div>

                <!-- Comments Section -->
                <div class="mt-5">
                    <h3 class="mb-4">Comments</h3>

                    <!-- Comment Form -->
                    <div class="card mb-4">
                        <div class="card-body">
                            <form method="post">
                                {%csrf_token%}
                                <div class="mb-3">
                                    {{form.text}}
                                </div>
                                <button type="submit" class="btn btn-primary">Submit Comment</button>
                            </form>
                        </div>
                    </div>

                    <!-- Individual Comments -->
                    <div class="comments">
                        <!-- Comment 1 -->
                        {%for com in comment%}
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <h6 class="card-subtitle mb-2 text-muted">{{com.user.username}}</h6>
                                    <small class="text-muted">{{com.created}}</small>
                                </div>
                                <p class="card-text">{{com.text}}</p>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/exhibition_edit.html
{% extends 'main/base.html' %}

{% block content %}
    <h1>Редактировать выставку</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="create-block">
            <div class="create-underblock"> {{ form.image }} </div>
        {{ form.name }} <br>
        {{ form.category }} <br>
        <button class="btn btn-success" type="submit">Add exhibition</button>
        </div>
        <div class="another-block">
            <div class="another-img">{{ form.image_4 }}
            <h6>{{ form.description_3 }}</h6></div>
        </div>
        <div class="block">
            <div class="img-block">
                <div class="image">{{ form.image_1 }}</div>
                <h3>{{ form.description }}</h3>
            </div>
            <div class="img-block">
                <div class="image">{{ form.image_2 }}</div>
                <h4>{{ form.description_2 }}</h4>
            </div>
            <div class="img-block">
                <div class="image">{{ form.image_3 }}</div>
                <h5>{{ form.description_1 }}</h5>
            </div>
        </div>

    </form>
    <a href="{% url 'articles:exhibition_detail' article.id %}" class="btn btn-secondary">Отмена</a>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static cache %}

{% block content %}
<div class="d-flex">
    <div class="m-5">
        <p>
          <button class="btn btn-primary" style="width: 200px;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
            Фильтры
          </button>
        </p>
        <div style="min-height: 120px;">
          <div class="collapse collapse-horizontal" id="collapseWidthExample">
            <div class="card card-body" style="width: 300px;">
                <a class="mb-3 btn btn-primary" href="#">По популярности</a>
                <a class="mb-3 btn btn-primary" href="#">По дате</a>
                <div class=" dropdown">
                  <button class="w-100 btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    По категории
                  </button>
                  <ul class="dropdown-menu">
                    <li class="card card-body">
                        {%for category in categories%}
                        <a class="btn btn-primary mb-3" href="{%url 'articles:category' category.id%}">{{category.name}}</a>
                        {%endfor%}
                    </li>
                  </ul>
                </div>
            </div>
          </div>
        </div>
    </div>
    <!-- Контент -->
    <div class="container py-5 p-5" style="margin-left: 20px;"> <!-- Отступ для бокового меню -->
        <h1 class="text-center mb-5">Выставки</h1>
        <div class="row gy-4">
            {% if object_list %}
            {%cache 30 object_list%}
            {% for el in object_list %}
            <div class="card bg-light m-5" style="width: 18rem;">
                <img src="{{ el.image.url }}" class="card-img-top mt-2 h-50" alt="...">
                <div class="card-body text-center">
                    <h5 class="card-title text-dark fs-3">{{el.name}}</h5>
                    <p class="card-text fs-5 text-start">{{el.description | truncatechars:50}}</p>
                    <p class="card-text text-start"><small class="text-body-secondary">{{el.created}}</small></p>
                    <a class="btn btn-success" href="{% url 'articles:exhibition_detail' id=el.id %}">Посмотреть выставку</a>
                </div>
            </div>
            {% endfor %}
            {%endcache%}
            {% else %}
                <p>На этой странице пока нету выставок</p>
            {% endif %}
        </div>
    </div>
</div>

<!--  <ul class="pagination">-->
<!--      {% if page_obj.has_previous %}-->
<!--    <li class="page-item">-->
<!--      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>-->
<!--    </li>-->
<!--      {%endif%}-->
<!--      {%for page in paginator.page_range%}-->
<!--    <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>-->
<!--      {%endfor%}-->
<!--      {% if page_obj.has_next %}-->
<!--    <li class="page-item">-->
<!--      <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>-->
<!--    </li>-->
<!--      {%endif%}-->
<!--  </ul>-->
</div>
{% endblock %}